"""Compile the pipeline's metrics and a reviewable sample of tablets with every output into samples/ (tracked).

  python -m line_cropping.report.compile_sample [--n 20] [--seed 11] [--out samples]

samples/
  README.md                 generated: what is here, how tablets were chosen, provenance
  metrics/METRICS.md        all headline numbers, regenerated from the result tables
  metrics/*.csv|json        the tables the numbers come from (Phase 5 test results, crop and OA evaluations,
                            confidence, tuned thresholds, split, ProtoSnap run summaries)
  ebl/<tablet>/...          per tablet: faces/, lines/ (crops), detections/, predictions/, truth_lines/, protosnap/
  ebl/{faces,crops}.csv     subsets of the pipeline tables for the sampled faces
  cdli/<tablet>/...         per tablet: faces/, lines/, detections/, predictions_profile/, predictions/, labels, protosnap/
  cdli/{faces,crops,labels,confidence}.csv
Selection (deterministic for a given --seed): eBL = 10 OB + 10 NA tablets with obverse and reverse cropped,
single-column, annotation coverage >= 0.9, dark background, preferring tablets that have ProtoSnap results and
test-split faces; CDLI = up to 10 tablets with hand-labelled lines (highest confidence first) + random tablets with
confidence >= 0.6, obverse and reverse both accepted and aligned with the CDLI ATF.
"""
import argparse, csv, os, glob, json, shutil, random, collections, subprocess, sys
import numpy as np, cv2

R = lambda p: list(csv.DictReader(open(p, encoding='utf-8'))) if os.path.exists(p) else []


def write_csv(path, rows):
    if not rows: return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', newline='', encoding='utf-8') as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)


def copy_image(src, dst, max_side=1600, q=85):
    im = cv2.imread(src)
    if im is None: return None
    s = min(1.0, max_side / max(im.shape[:2]))
    if s < 1: im = cv2.resize(im, None, fx=s, fy=s, interpolation=cv2.INTER_AREA)
    os.makedirs(os.path.dirname(dst), exist_ok=True); cv2.imwrite(dst, im, [cv2.IMWRITE_JPEG_QUALITY, q]); return s


def run_capture(cmd):
    try: return subprocess.run(cmd, capture_output=True, text=True, timeout=1800).stdout.strip()
    except Exception as e: return f'(could not run: {e})'


# ------------------------------------------------------------------ metrics
def compile_metrics(out):
    m = os.path.join(out, 'metrics'); os.makedirs(m, exist_ok=True); md = ['# Metrics', '', 'Regenerated by `python -m line_cropping.report.compile_sample`. Definitions: a line is matched within 0.35 pitch of a truth centre; precision only on faces with coverage >= 0.9; first-line error only where the topmost truth line is 1 or 1\'.', '']
    # inventory
    faces = R('ebl_tablets/faces/faces.csv'); tabs = R('ebl_tablets/ground_truth/tablets.csv'); man = R('ebl_tablets/manifest.csv')
    md += ['## Data', '', f'- eBL tablets downloaded: {len(man)} ({collections.Counter(r["script"] for r in man)["NA"]} NA, {collections.Counter(r["script"] for r in man)["OB"]} OB); with line ground truth: {len(tabs)}; sign boxes: {sum(int(t["n_signs"]) for t in tabs) if tabs else 0}; truth lines: {sum(int(t["n_lines"]) for t in tabs) if tabs else 0}',
           f'- eBL faces cut: {len(faces)}; median px per line {np.median([float(f["pitch_px"]) for f in faces if f["pitch_px"]]):.0f}' if faces else '']
    oa_inv = R('fat-cross_processed/inventory.csv'); oa_acc = R('fat-cross_processed/prepared/faces_accepted.csv')
    md += [f'- CDLI Old Assyrian tablets: {len(oa_inv)}; with ATF: {sum(r["has_atf"]=="True" for r in oa_inv)}; accepted faces: {len(oa_acc)}', '']
    # phase 5 test results
    p5 = R('ebl_tablets/phase5_test_results.csv')
    if p5:
        shutil.copy2('ebl_tablets/phase5_test_results.csv', m); 
        for f in ('det_params.json', 'split.csv'):
            if os.path.exists(f'ebl_tablets/{f}'): shutil.copy2(f'ebl_tablets/{f}', m)
        md += ['## Line finding on eBL faces, test split (Phase 5)', '', '| method | group | n | recall | precision | first line < 0.5 pitch | count match |', '|---|---|---|---|---|---|---|']
        def agg(rows):
            rec = np.mean([float(r['recall']) for r in rows]); pr = [float(r['precision']) for r in rows if r['precision']]; fe = [float(r['first_err']) for r in rows if r['first_err']]
            return f"{len(rows)} | {rec:.2f} | {np.mean(pr) if pr else float('nan'):.2f} | {np.mean(np.array(fe) < 0.5) if fe else float('nan'):.0%} | {np.mean([r['count_ok']=='True' for r in rows]):.0%}"
        for meth in ('det_n', 'det'):
            rows = [r for r in p5 if r['method'] == meth]; md.append(f'| {meth} | all | {agg(rows)} |')
            for g in sorted({r['bucket'] for r in rows}): md.append(f'| {meth} | {g} | {agg([r for r in rows if r["bucket"] == g])} |')
        hi = [r for r in p5 if r['method'] == 'det_n' and float(r['px_per_line']) >= 120]
        md += ['', f'Plan criteria (det_n, >= 120 px/line, n={len(hi)}): ' + agg(hi).split(' | ', 1)[1] + '  (targets: recall 0.90, first line 90%, count 80%)', '']
        if os.path.exists('ebl_tablets/predictions/det_params.json'): pass
    # all-face evaluation and crop evaluation via the evaluators
    md += ['## Line finding on all eBL faces (all methods)', '', '```', run_capture([sys.executable, '-W', 'ignore', '-m', 'line_cropping.eval.evaluate_lines', '--faces', 'ebl_tablets/faces/faces.csv', '--pred', 'ebl_tablets/predictions']), '```', '']
    if os.path.exists('ebl_tablets/predictions/evaluation.csv'): shutil.copy2('ebl_tablets/predictions/evaluation.csv', os.path.join(m, 'evaluation_lines_ebl.csv'))
    md += ['## Line crops on eBL faces (Phase 4, gap-bounded)', '', '```', run_capture([sys.executable, '-W', 'ignore', '-m', 'line_cropping.eval.evaluate_crops', '--faces', 'ebl_tablets/faces/faces.csv', '--crops', 'ebl_tablets/line_crops/crops.csv']), '```', '']
    if os.path.exists('fat-cross_processed/ground_truth/labels.csv'):
        md += ['## Old Assyrian faces against hand labels', '', '```', run_capture([sys.executable, '-W', 'ignore', '-m', 'line_cropping.eval.evaluate_oa']), '```', '']
        for f in ('ground_truth/evaluation_oa.csv', 'ground_truth/labels.csv', 'confidence.csv'):
            if os.path.exists(f'fat-cross_processed/{f}'): shutil.copy2(f'fat-cross_processed/{f}', os.path.join(m, 'oa_' + os.path.basename(f)))
    conf = R('fat-cross_processed/confidence.csv')
    if conf:
        c = np.array([float(r['confidence']) for r in conf if r['confidence']]); a = np.array([float(r['agreement']) for r in conf if r['agreement']])
        md += ['## Old Assyrian confidence without truth', '', f'- faces scored {len(conf)}; median confidence {np.median(c):.2f}, lowest decile below {np.percentile(c, 10):.2f}; median dp-vs-det_n agreement {np.median(a):.2f}', '']
    # ProtoSnap runs
    md += ['## ProtoSnap runs', '']
    for run in sorted(glob.glob('output/phase6_*')):
        sm = R(os.path.join(run, 'summary.csv'))
        if not sm: continue
        shutil.copy2(os.path.join(run, 'summary.csv'), os.path.join(m, f'protosnap_{os.path.basename(run)}_summary.csv'))
        sc = [float(r['init_score']) for r in sm if r['init_score']]
        md.append(f'- `{run}`: {len(sm)} targets, {sum(r["finished"]=="True" for r in sm)} finished, init score median {np.median(sc):.2f} (curated single-sign test set: 0.75)')
    md.append('')
    open(os.path.join(m, 'METRICS.md'), 'w', encoding='utf-8').write('\n'.join(md)); print('metrics ->', os.path.join(m, 'METRICS.md'))


# ------------------------------------------------------------------ samples
def protosnap_for_faces(faceset):
    """ProtoSnap results (targets, summary rows, overlays) that belong to the given faces."""
    out = []
    for run in sorted(glob.glob('output/phase6_*')):
        for r in R(os.path.join(run, 'summary.csv')):
            face = r['target'].split('__L')[0]
            if face in faceset: out.append((run, r))
    return out


def copy_protosnap(items, dest):
    rows = []
    for run, r in items:
        d = os.path.join(dest, 'protosnap', os.path.basename(run), r['target']); os.makedirs(d, exist_ok=True)
        src = os.path.join(run, r['target'] + '_results')
        for f in ('itr99_viz.png', 'final_result_100.png', 'init.png'):
            if os.path.exists(os.path.join(src, f)): shutil.copy2(os.path.join(src, f), d)
        face = r['target'].split('__L')[0]; line = r['target'].split('__')[2]
        for kind, name in (('faces', face + '.jpg'), ('lines', f'{face}__{line}.jpg')):
            p = os.path.join(run, 'overlays', kind, name)
            if os.path.exists(p): shutil.copy2(p, os.path.join(d, f'overlay_{kind[:-1]}.jpg'))
        rr = dict(r); rr['run'] = os.path.basename(run); rows.append(rr)
    return rows


def sample_ebl(out, n, seed):
    faces = R('ebl_tablets/faces/faces.csv'); crops = collections.defaultdict(list)
    for r in R('ebl_tablets/line_crops/crops.csv'): crops[r['face']].append(r)
    split = {r['face']: r['split'] for r in R('ebl_tablets/split.csv')}
    ps_faces = {r['target'].split('__L')[0] for run in glob.glob('output/phase6_*') for r in R(os.path.join(run, 'summary.csv'))}
    by = collections.defaultdict(list)
    for f in faces:
        if f['face'] in crops: by[f['tablet']].append(f)
    cands = []
    for tab, fs in by.items():
        if not {'obverse', 'reverse'} <= {f['side'] for f in fs}: continue
        if any(f['n_columns'] != '1' or not f['coverage'] or float(f['coverage']) < 0.9 or int(f['background']) >= 128 for f in fs): continue
        lines = sum(len(crops[f['face']]) for f in fs)
        if not 6 <= lines <= 60: continue
        cands.append(dict(tablet=tab, script=fs[0]['script'], has_ps=any(f['face'] in ps_faces for f in fs), test=all(split.get(f['face']) == 'test' for f in fs)))
    random.seed(seed); pick = []
    for sc in ('OB', 'NA'):
        pool = [c for c in cands if c['script'] == sc]; random.shuffle(pool); pool.sort(key=lambda c: (not c['has_ps'], not c['test']))
        pick += pool[:n // 2]
    tablets = {c['tablet'] for c in pick}; root = os.path.join(out, 'ebl'); of, oc = [], []
    for f in faces:
        if f['tablet'] not in tablets or f['face'] not in crops: continue
        d = os.path.join(root, f['tablet']); s = copy_image(f['file'], os.path.join(d, 'faces', f['face'] + '.jpg'))
        ff = dict(f); ff['file'] = os.path.join(d, 'faces', f['face'] + '.jpg'); ff['face_image_scale'] = s; of.append(ff)
        for c in crops[f['face']]:
            dst = os.path.join(d, 'lines', os.path.basename(c['crop'])); copy_image(c['crop'], dst, max_side=1600, q=85); cc = dict(c); cc['crop'] = dst; oc.append(cc)
        for sub, src in (('detections', f'ebl_tablets/detections/{f["face"]}.csv'), ('predictions', f'ebl_tablets/predictions/det_n/{f["face"]}.csv'), ('predictions_no_count', f'ebl_tablets/predictions/det/{f["face"]}.csv'), ('truth_lines', f'ebl_tablets/faces/lines/{f["face"]}.csv')):
            if os.path.exists(src): os.makedirs(os.path.join(d, sub), exist_ok=True); shutil.copy2(src, os.path.join(d, sub, f['face'] + '.csv'))
    write_csv(os.path.join(root, 'faces.csv'), of); write_csv(os.path.join(root, 'crops.csv'), oc)
    ps = copy_protosnap(protosnap_for_faces({f['face'] for f in of}), root); write_csv(os.path.join(root, 'protosnap_results.csv'), ps)
    return dict(tablets=sorted(tablets), faces=len(of), crops=len(oc), protosnap=len(ps), scripts=collections.Counter(c['script'] for c in pick))


def sample_cdli(out, n, seed):
    faces = R('fat-cross_processed/prepared/faces_accepted.csv'); crops = collections.defaultdict(list)
    for r in R('fat-cross_processed/line_crops/crops.csv'): crops[r['face']].append(r)
    conf = {r['face']: r for r in R('fat-cross_processed/confidence.csv') if r['confidence']}
    labels = R('fat-cross_processed/ground_truth/labels.csv'); labelled = {r['face_id'] for r in labels if r['status'] == 'done'}
    by = collections.defaultdict(list)
    for f in faces:
        if f['face'] in crops: by[f['p_number']].append(f)
    cands = []
    for p, fs in by.items():
        if not {'obverse', 'reverse'} <= {f['side'] for f in fs}: continue
        if not all(crops[f['face']][0]['atf_aligned'] == 'True' for f in fs if f['side'] in ('obverse', 'reverse')): continue
        c = [float(conf[f['face']]['confidence']) for f in fs if f['face'] in conf]
        cands.append(dict(p=p, conf=float(np.mean(c)) if c else 0.0, labelled=any(f['face'] in labelled for f in fs)))
    random.seed(seed); lab = sorted([c for c in cands if c['labelled']], key=lambda c: -c['conf'])[:n // 2]
    rest = [c for c in cands if not c['labelled'] and c['conf'] >= 0.6]; random.shuffle(rest); pick = lab + rest[:n - len(lab)]
    tablets = {c['p'] for c in pick}; root = os.path.join(out, 'cdli'); of, oc = [], []
    for f in faces:
        if f['p_number'] not in tablets or f['face'] not in crops: continue
        d = os.path.join(root, f['p_number']); s = copy_image(f['file'], os.path.join(d, 'faces', f['face'] + '.jpg'))
        ff = dict(f); ff['file'] = os.path.join(d, 'faces', f['face'] + '.jpg'); ff['face_image_scale'] = s; of.append(ff)
        for c in crops[f['face']]:
            dst = os.path.join(d, 'lines', os.path.basename(c['crop'])); copy_image(c['crop'], dst, max_side=1600, q=85); cc = dict(c); cc['crop'] = dst; oc.append(cc)
        for sub, src in (('detections', f'fat-cross_processed/detections/{f["face"]}.csv'), ('predictions_profile', f'fat-cross_processed/predictions_profile/dp/{f["face"]}.csv'), ('predictions_detector', f'fat-cross_processed/predictions/det_n/{f["face"]}.csv')):
            if os.path.exists(src): os.makedirs(os.path.join(d, sub), exist_ok=True); shutil.copy2(src, os.path.join(d, sub, f['face'] + '.csv'))
    fs = {f['face'] for f in of}
    write_csv(os.path.join(root, 'faces.csv'), of); write_csv(os.path.join(root, 'crops.csv'), oc)
    write_csv(os.path.join(root, 'labels.csv'), [r for r in labels if r['face_id'] in fs]); write_csv(os.path.join(root, 'confidence.csv'), [conf[f] for f in fs if f in conf])
    ps = copy_protosnap(protosnap_for_faces(fs), root); write_csv(os.path.join(root, 'protosnap_results.csv'), ps)
    return dict(tablets=sorted(tablets), faces=len(of), crops=len(oc), protosnap=len(ps), labelled=sum(1 for c in pick if c['labelled']))


def write_readme(out, e, c, n, seed):
    txt = f'''# Sample outputs and metrics

Generated by `python -m line_cropping.report.compile_sample --n {n} --seed {seed}` (see `line_cropping/README.md` and
`docs/pipeline_overview.md`). The full data sets are gitignored; this folder holds every metric and a reviewable sample.

- `metrics/METRICS.md` — all headline numbers, with the tables they come from beside it.
- `ebl/` — {len(e['tablets'])} eBL tablets ({dict(e['scripts'])}), {e['faces']} faces, {e['crops']} gap-bounded line crops, {e['protosnap']} ProtoSnap results.
- `cdli/` — {len(c['tablets'])} CDLI Old Assyrian tablets ({c['labelled']} with hand-labelled lines), {c['faces']} faces, {c['crops']} midpoint line crops, {c['protosnap']} ProtoSnap results.

Per tablet: `faces/` (extracted face, longest side <= 1600 px; scale in `faces.csv`), `lines/` (one crop per line in
reading order, re-encoded at JPEG quality 85), `detections/` (eBL detector boxes), `predictions*/` (line centres), and for eBL `truth_lines/`
(eBL-derived line ground truth); `protosnap/<run>/<target>/` holds ProtoSnap's alignment renders and the overlays on
the face and on the line crop where a sign of that face was run. `crops.csv` maps every crop back to its face and,
when the count matched the transliteration, to its ATF line.

Selection: eBL tablets have obverse and reverse cropped, single column, annotation coverage >= 0.9, dark background,
preferring tablets with ProtoSnap results and test-split faces; CDLI tablets have both faces accepted and aligned
with the CDLI ATF, the first half drawn from the hand-labelled faces (highest confidence first), the rest random among
faces with confidence >= 0.6.

Provenance: photographs are museum images redistributed by the Electronic Babylonian Library (https://www.ebl.lmu.de/)
and the Cuneiform Digital Library Initiative (https://cdli.mpiwg-berlin.mpg.de/); copyright remains with the holding
institutions (British Museum images CC BY-NC-SA 4.0; others vary) and the sample is for research use. Transliterations
are from eBL and CDLI. Detections come from the eBL Deformable DETR detector (Zenodo 17395154, CC BY 4.0).

eBL tablets: {', '.join(e['tablets'])}
CDLI tablets: {', '.join(c['tablets'])}
'''
    open(os.path.join(out, 'README.md'), 'w', encoding='utf-8').write(txt)


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--n', type=int, default=20); ap.add_argument('--seed', type=int, default=11); ap.add_argument('--out', default='samples')
    a = ap.parse_args()
    if os.path.exists(a.out): shutil.rmtree(a.out)
    os.makedirs(a.out); compile_metrics(a.out)
    e = sample_ebl(a.out, a.n, a.seed); print('ebl sample:', {k: v for k, v in e.items() if k != 'tablets'})
    c = sample_cdli(a.out, a.n, a.seed); print('cdli sample:', {k: v for k, v in c.items() if k != 'tablets'})
    write_readme(a.out, e, c, a.n, a.seed)
    total = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(a.out) for f in fs); print(f'{a.out}/ written: {total/1e6:.0f} MB')


if __name__ == '__main__':
    main()
